using ITS.Retail.Platform.Enumerations;
using ITS.Retail.Platform.Kernel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ITS.Retail.Platform.Promotions
{
    /// <summary>
    ///  Promotion criteria for the customer of the document.
    /// </summary>
    public class PromotionCustomerCriteria : IPromotionCriteria
    {
        /// <summary>
        /// The customer to filter with.
        /// </summary>
        public Guid Customer { get; protected set; }

        public PromotionCustomerCriteria(Guid customer)
        {
            this.Customer = customer;
        }

        /// <summary>
        /// Returns true if the document's customerID is the Customer.
        /// </summary>
        /// <param name="denormalizedDocument"></param>
        /// <param name="priority"></param>
        /// <returns></returns>
        public bool MeetCriteria(List<DenormalizedDocumentDataLine> denormalizedDocument, ePromotionExecutionPriority priority)
        {
            List<DenormalizedDocumentDataLine> result = new List<DenormalizedDocumentDataLine>();

            if (this.Customer != Guid.Empty) //Check for GrossTotalBeforeDocumentDiscount 
            {
                result.AddRange(denormalizedDocument.Where(x => x.Customer.Oid == this.Customer));
            }
            else
            {
                throw new Exception("Customer cannot be empty");
            }

            return result.Count > 0;
        }

        /// <summary>
        /// Gets a list of constrains that are generated by applying this criteria.
        /// </summary>
        /// <param name="denormalizedDocument"></param>
        /// <param name="priority"></param>
        /// <returns></returns>
        public List<IPromotionConstrain> GetConstrains(List<DenormalizedDocumentDataLine> denormalizedDocument,ePromotionExecutionPriority priority)
        {
            ////no constrains
            return new List<IPromotionConstrain>();
        }

    }
}
