using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using ITS.POS.Client.ObserverPattern;
using ITS.POS.Model.Transactions;
using ITS.Retail.Platform.Enumerations;
using DevExpress.XtraGrid.Views.Grid;
using ITS.POS.Resources;
using ITS.POS.Client.Kernel;

namespace ITS.POS.Client.Forms
{
    public partial class frmDocumentsOnHold : frmDialogBase
    {
        public frmDocumentsOnHold(IPosKernel kernel) : base(kernel)
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            IAppContext appContext = kernel.GetModule<IAppContext>();
            grdDocumentsOnHold.DataSource = appContext.DocumentsOnHold;
            gridColumn1.Caption = POSClientResources.DATE.ToUpperGR();
            gridColumn2.Caption = POSClientResources.AMOUNT.ToUpperGR();
        }

        public DocumentHeader SelectedObject { get; set; }


        public override void Update(ObserverPattern.ObserverParameters.KeyListenerParams parameters)
        {
            base.Update(parameters);
            GridView view = ((GridView)grdDocumentsOnHold.MainView);
            if (parameters.NotificationType == eNotificationsTypes.ACTION && parameters.ActionCode == eActions.MOVE_UP)
            {
                if (view.FocusedRowHandle > 0)
                {
                    view.FocusedRowHandle--;
                }
            }
            else if (parameters.NotificationType == eNotificationsTypes.ACTION && parameters.ActionCode == eActions.MOVE_DOWN)
            {
                if (view.FocusedRowHandle >= 0 && view.FocusedRowHandle < (view.RowCount - 1))
                {
                    view.FocusedRowHandle++;   
                }
            }
            else if (parameters.NotificationType == eNotificationsTypes.KEY && parameters.KeyData == Keys.Enter)
            {
                btnOK.PerformClick();
            }
        }

        private void btnOK_Click(object sender, EventArgs e)
        {
            SelectedObject = ((GridView)grdDocumentsOnHold.MainView).GetFocusedRow() as DocumentHeader;
            DialogResult = DialogResult.OK;
        }

        private void btnClose_Click(object sender, EventArgs e)
        {
            SelectedObject = null;
            DialogResult = DialogResult.Cancel;
        }
    }
}
