//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITS.Retail.DesktopClient.StoreControllerClient.ITSStoreControllerDesktopService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ITSStoreControllerDesktopService.IITSStoreControllerDesktopService")]
    public interface IITSStoreControllerDesktopService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IITSStoreControllerDesktopService/SendPOSCommands", ReplyAction="http://tempuri.org/IITSStoreControllerDesktopService/SendPOSCommandsResponse")]
        bool SendPOSCommands(POSCommandsLibrary.POSCommandDescription[] commands);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IITSStoreControllerDesktopService/SendMasterInfo", ReplyAction="http://tempuri.org/IITSStoreControllerDesktopService/SendMasterInfoResponse")]
        bool SendMasterInfo(out ITS.Retail.Platform.Enumerations.eApplicationInstance appInstance, out string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IITSStoreControllerDesktopService/GetDbType", ReplyAction="http://tempuri.org/IITSStoreControllerDesktopService/GetDbTypeResponse")]
        DBType GetDbType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IITSStoreControllerDesktopService/GetNowTicks", ReplyAction="http://tempuri.org/IITSStoreControllerDesktopService/GetNowTicksResponse")]
        long GetNowTicks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IITSStoreControllerDesktopService/GetApplicationStatus", ReplyAction="http://tempuri.org/IITSStoreControllerDesktopService/GetApplicationStatusResponse" +
            "")]
        ITS.Retail.Platform.Enumerations.ApplicationStatus GetApplicationStatus();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IITSStoreControllerDesktopServiceChannel : ITS.Retail.DesktopClient.StoreControllerClient.ITSStoreControllerDesktopService.IITSStoreControllerDesktopService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ITSStoreControllerDesktopServiceClient : System.ServiceModel.ClientBase<ITS.Retail.DesktopClient.StoreControllerClient.ITSStoreControllerDesktopService.IITSStoreControllerDesktopService>, ITS.Retail.DesktopClient.StoreControllerClient.ITSStoreControllerDesktopService.IITSStoreControllerDesktopService {
        
        public ITSStoreControllerDesktopServiceClient() {
        }
        
        public ITSStoreControllerDesktopServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ITSStoreControllerDesktopServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ITSStoreControllerDesktopServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ITSStoreControllerDesktopServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SendPOSCommands(POSCommandsLibrary.POSCommandDescription[] commands) {
            return base.Channel.SendPOSCommands(commands);
        }
        
        public bool SendMasterInfo(out ITS.Retail.Platform.Enumerations.eApplicationInstance appInstance, out string url) {
            return base.Channel.SendMasterInfo(out appInstance, out url);
        }
        
        public DBType GetDbType() {
            return base.Channel.GetDbType();
        }
        
        public long GetNowTicks() {
            return base.Channel.GetNowTicks();
        }
        
        public ITS.Retail.Platform.Enumerations.ApplicationStatus GetApplicationStatus() {
            return base.Channel.GetApplicationStatus();
        }
    }
}
