//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.5477.
// 
namespace Retail.Mobile.RetailService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RetailServiceSoap", Namespace="https://weborders.masoutis.gr/")]
    public partial class RetailService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public RetailService() {
            this.Url = "http://localhost/its.retail.webclient/retailservice.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/Login", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Guid Login(string username, string pass, int type) {
            object[] results = this.Invoke("Login", new object[] {
                        username,
                        pass,
                        type});
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLogin(string username, string pass, int type, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Login", new object[] {
                        username,
                        pass,
                        type}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Guid EndLogin(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/PostData", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PostData(string typeName, string data, string device) {
            object[] results = this.Invoke("PostData", new object[] {
                        typeName,
                        data,
                        device});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPostData(string typeName, string data, string device, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PostData", new object[] {
                        typeName,
                        data,
                        device}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndPostData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetSeries", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSeries(string Userid, int mode) {
            object[] results = this.Invoke("GetSeries", new object[] {
                        Userid,
                        mode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSeries(string Userid, int mode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSeries", new object[] {
                        Userid,
                        mode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetSeries(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetDocumentStatus", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TDocumentStatus[] GetDocumentStatus() {
            object[] results = this.Invoke("GetDocumentStatus", new object[0]);
            return ((TDocumentStatus[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDocumentStatus(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDocumentStatus", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public TDocumentStatus[] EndGetDocumentStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TDocumentStatus[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetItem", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetItem(string Sfilter, string Sfields, string UserID) {
            object[] results = this.Invoke("GetItem", new object[] {
                        Sfilter,
                        Sfields,
                        UserID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetItem(string Sfilter, string Sfields, string UserID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetItem", new object[] {
                        Sfilter,
                        Sfields,
                        UserID}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetItem(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetItemWithBarcodeCustomer", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetItemWithBarcodeCustomer(string barcode, string Sfields, string CustomerID) {
            object[] results = this.Invoke("GetItemWithBarcodeCustomer", new object[] {
                        barcode,
                        Sfields,
                        CustomerID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetItemWithBarcodeCustomer(string barcode, string Sfields, string CustomerID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetItemWithBarcodeCustomer", new object[] {
                        barcode,
                        Sfields,
                        CustomerID}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetItemWithBarcodeCustomer(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetItemWithBarcode", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetItemWithBarcode(string barcode, string Sfields, string UserID) {
            object[] results = this.Invoke("GetItemWithBarcode", new object[] {
                        barcode,
                        Sfields,
                        UserID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetItemWithBarcode(string barcode, string Sfields, string UserID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetItemWithBarcode", new object[] {
                        barcode,
                        Sfields,
                        UserID}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetItemWithBarcode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetPrice", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPrice(string UserID, string ItemOid, string barcode) {
            object[] results = this.Invoke("GetPrice", new object[] {
                        UserID,
                        ItemOid,
                        barcode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPrice(string UserID, string ItemOid, string barcode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPrice", new object[] {
                        UserID,
                        ItemOid,
                        barcode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetPrice(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetPriceCustomer", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double GetPriceCustomer(string CustomerID, string ItemOid, string barcode) {
            object[] results = this.Invoke("GetPriceCustomer", new object[] {
                        CustomerID,
                        ItemOid,
                        barcode});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPriceCustomer(string CustomerID, string ItemOid, string barcode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPriceCustomer", new object[] {
                        CustomerID,
                        ItemOid,
                        barcode}, callback, asyncState);
        }
        
        /// <remarks/>
        public double EndGetPriceCustomer(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetDocumentDetailCustomer", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TransferedDocumentDetail[] GetDocumentDetailCustomer(string customerString, string barcode, double qty) {
            object[] results = this.Invoke("GetDocumentDetailCustomer", new object[] {
                        customerString,
                        barcode,
                        qty});
            return ((TransferedDocumentDetail[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDocumentDetailCustomer(string customerString, string barcode, double qty, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDocumentDetailCustomer", new object[] {
                        customerString,
                        barcode,
                        qty}, callback, asyncState);
        }
        
        /// <remarks/>
        public TransferedDocumentDetail[] EndGetDocumentDetailCustomer(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TransferedDocumentDetail[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetDocumentDetail", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TransferedDocumentDetail[] GetDocumentDetail(string userid, string barcode, double qty) {
            object[] results = this.Invoke("GetDocumentDetail", new object[] {
                        userid,
                        barcode,
                        qty});
            return ((TransferedDocumentDetail[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDocumentDetail(string userid, string barcode, double qty, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDocumentDetail", new object[] {
                        userid,
                        barcode,
                        qty}, callback, asyncState);
        }
        
        /// <remarks/>
        public TransferedDocumentDetail[] EndGetDocumentDetail(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TransferedDocumentDetail[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/ValidateOrder", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TInvalidItem[] ValidateOrder(string data) {
            object[] results = this.Invoke("ValidateOrder", new object[] {
                        data});
            return ((TInvalidItem[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginValidateOrder(string data, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ValidateOrder", new object[] {
                        data}, callback, asyncState);
        }
        
        /// <remarks/>
        public TInvalidItem[] EndValidateOrder(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TInvalidItem[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/PostDocument", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PostDocument(string data) {
            object[] results = this.Invoke("PostDocument", new object[] {
                        data});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPostDocument(string data, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PostDocument", new object[] {
                        data}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndPostDocument(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetVersion", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetVersion() {
            object[] results = this.Invoke("GetVersion", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetVersion(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetVersion", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetVersion(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetUserType", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserType GetUserType(string userid) {
            object[] results = this.Invoke("GetUserType", new object[] {
                        userid});
            return ((UserType)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUserType(string userid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUserType", new object[] {
                        userid}, callback, asyncState);
        }
        
        /// <remarks/>
        public UserType EndGetUserType(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UserType)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetCustomersOfUser", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TCustomer[] GetCustomersOfUser(string userid, long updatedOn) {
            object[] results = this.Invoke("GetCustomersOfUser", new object[] {
                        userid,
                        updatedOn});
            return ((TCustomer[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCustomersOfUser(string userid, long updatedOn, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCustomersOfUser", new object[] {
                        userid,
                        updatedOn}, callback, asyncState);
        }
        
        /// <remarks/>
        public TCustomer[] EndGetCustomersOfUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TCustomer[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetCustomers", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TCustomer[] GetCustomers(long updatedOn, string userID) {
            object[] results = this.Invoke("GetCustomers", new object[] {
                        updatedOn,
                        userID});
            return ((TCustomer[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCustomers(long updatedOn, string userID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCustomers", new object[] {
                        updatedOn,
                        userID}, callback, asyncState);
        }
        
        /// <remarks/>
        public TCustomer[] EndGetCustomers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TCustomer[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetTotalUpdates", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetTotalUpdates(
                    long Customerupdatedon, 
                    long Itemupdatedon, 
                    long IATupdatedon, 
                    long Barcodeupdatedon, 
                    long ICupdatedon, 
                    long PCupdatedon, 
                    long PCDupdatedon, 
                    long VCupdatedon, 
                    long VFupdatedon, 
                    long VLupdatedon, 
                    long offerUpdatedOn, 
                    long offerDetailUpdatedOn, 
                    long documentStatusUpdatedOn, 
                    long storesUpdatedOn, 
                    long linkedItemsUpdatedOn, 
                    long mmUpdatedOn, 
                    long documentTypeUpdatedOn, 
                    string userID) {
            object[] results = this.Invoke("GetTotalUpdates", new object[] {
                        Customerupdatedon,
                        Itemupdatedon,
                        IATupdatedon,
                        Barcodeupdatedon,
                        ICupdatedon,
                        PCupdatedon,
                        PCDupdatedon,
                        VCupdatedon,
                        VFupdatedon,
                        VLupdatedon,
                        offerUpdatedOn,
                        offerDetailUpdatedOn,
                        documentStatusUpdatedOn,
                        storesUpdatedOn,
                        linkedItemsUpdatedOn,
                        mmUpdatedOn,
                        documentTypeUpdatedOn,
                        userID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTotalUpdates(
                    long Customerupdatedon, 
                    long Itemupdatedon, 
                    long IATupdatedon, 
                    long Barcodeupdatedon, 
                    long ICupdatedon, 
                    long PCupdatedon, 
                    long PCDupdatedon, 
                    long VCupdatedon, 
                    long VFupdatedon, 
                    long VLupdatedon, 
                    long offerUpdatedOn, 
                    long offerDetailUpdatedOn, 
                    long documentStatusUpdatedOn, 
                    long storesUpdatedOn, 
                    long linkedItemsUpdatedOn, 
                    long mmUpdatedOn, 
                    long documentTypeUpdatedOn, 
                    string userID, 
                    System.AsyncCallback callback, 
                    object asyncState) {
            return this.BeginInvoke("GetTotalUpdates", new object[] {
                        Customerupdatedon,
                        Itemupdatedon,
                        IATupdatedon,
                        Barcodeupdatedon,
                        ICupdatedon,
                        PCupdatedon,
                        PCDupdatedon,
                        VCupdatedon,
                        VFupdatedon,
                        VLupdatedon,
                        offerUpdatedOn,
                        offerDetailUpdatedOn,
                        documentStatusUpdatedOn,
                        storesUpdatedOn,
                        linkedItemsUpdatedOn,
                        mmUpdatedOn,
                        documentTypeUpdatedOn,
                        userID}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndGetTotalUpdates(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/getUserStoreAccess", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TUserStoreAccess[] getUserStoreAccess(string userID) {
            object[] results = this.Invoke("getUserStoreAccess", new object[] {
                        userID});
            return ((TUserStoreAccess[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetUserStoreAccess(string userID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getUserStoreAccess", new object[] {
                        userID}, callback, asyncState);
        }
        
        /// <remarks/>
        public TUserStoreAccess[] EndgetUserStoreAccess(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TUserStoreAccess[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/getStores", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TStore[] getStores(long updatedon, string userID) {
            object[] results = this.Invoke("getStores", new object[] {
                        updatedon,
                        userID});
            return ((TStore[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetStores(long updatedon, string userID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getStores", new object[] {
                        updatedon,
                        userID}, callback, asyncState);
        }
        
        /// <remarks/>
        public TStore[] EndgetStores(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TStore[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/getAppSettings", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TAppSettings getAppSettings(string userID) {
            object[] results = this.Invoke("getAppSettings", new object[] {
                        userID});
            return ((TAppSettings)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAppSettings(string userID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAppSettings", new object[] {
                        userID}, callback, asyncState);
        }
        
        /// <remarks/>
        public TAppSettings EndgetAppSettings(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TAppSettings)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/CleanFile", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CleanFile(string filename, string userID) {
            object[] results = this.Invoke("CleanFile", new object[] {
                        filename,
                        userID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCleanFile(string filename, string userID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CleanFile", new object[] {
                        filename,
                        userID}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndCleanFile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetTotalUpdatesLink", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTotalUpdatesLink(
                    long Customerupdatedon, 
                    long Itemupdatedon, 
                    long IATupdatedon, 
                    long Barcodeupdatedon, 
                    long ICupdatedon, 
                    long PCupdatedon, 
                    long PCDupdatedon, 
                    long VCupdatedon, 
                    long VFupdatedon, 
                    long VLupdatedon, 
                    long offerUpdatedOn, 
                    long offerDetailUpdatedOn, 
                    long documentStatusUpdatedOn, 
                    long storesUpdatedOn, 
                    long linkedItemsUpdatedOn, 
                    long mmUpdatedOn, 
                    long documentTypeUpdatedOn, 
                    string userID) {
            object[] results = this.Invoke("GetTotalUpdatesLink", new object[] {
                        Customerupdatedon,
                        Itemupdatedon,
                        IATupdatedon,
                        Barcodeupdatedon,
                        ICupdatedon,
                        PCupdatedon,
                        PCDupdatedon,
                        VCupdatedon,
                        VFupdatedon,
                        VLupdatedon,
                        offerUpdatedOn,
                        offerDetailUpdatedOn,
                        documentStatusUpdatedOn,
                        storesUpdatedOn,
                        linkedItemsUpdatedOn,
                        mmUpdatedOn,
                        documentTypeUpdatedOn,
                        userID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTotalUpdatesLink(
                    long Customerupdatedon, 
                    long Itemupdatedon, 
                    long IATupdatedon, 
                    long Barcodeupdatedon, 
                    long ICupdatedon, 
                    long PCupdatedon, 
                    long PCDupdatedon, 
                    long VCupdatedon, 
                    long VFupdatedon, 
                    long VLupdatedon, 
                    long offerUpdatedOn, 
                    long offerDetailUpdatedOn, 
                    long documentStatusUpdatedOn, 
                    long storesUpdatedOn, 
                    long linkedItemsUpdatedOn, 
                    long mmUpdatedOn, 
                    long documentTypeUpdatedOn, 
                    string userID, 
                    System.AsyncCallback callback, 
                    object asyncState) {
            return this.BeginInvoke("GetTotalUpdatesLink", new object[] {
                        Customerupdatedon,
                        Itemupdatedon,
                        IATupdatedon,
                        Barcodeupdatedon,
                        ICupdatedon,
                        PCupdatedon,
                        PCDupdatedon,
                        VCupdatedon,
                        VFupdatedon,
                        VLupdatedon,
                        offerUpdatedOn,
                        offerDetailUpdatedOn,
                        documentStatusUpdatedOn,
                        storesUpdatedOn,
                        linkedItemsUpdatedOn,
                        mmUpdatedOn,
                        documentTypeUpdatedOn,
                        userID}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetTotalUpdatesLink(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/CheckValidStorePriceCatalogPair", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckValidStorePriceCatalogPair(string store, string priceCatalog) {
            object[] results = this.Invoke("CheckValidStorePriceCatalogPair", new object[] {
                        store,
                        priceCatalog});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCheckValidStorePriceCatalogPair(string store, string priceCatalog, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CheckValidStorePriceCatalogPair", new object[] {
                        store,
                        priceCatalog}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndCheckValidStorePriceCatalogPair(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetDocumentHeaders", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TDocumentHeader[] GetDocumentHeaders(string userid, string customerid) {
            object[] results = this.Invoke("GetDocumentHeaders", new object[] {
                        userid,
                        customerid});
            return ((TDocumentHeader[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDocumentHeaders(string userid, string customerid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDocumentHeaders", new object[] {
                        userid,
                        customerid}, callback, asyncState);
        }
        
        /// <remarks/>
        public TDocumentHeader[] EndGetDocumentHeaders(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TDocumentHeader[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetDocumentHeadersXML", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDocumentHeadersXML(string userid, string customerid) {
            object[] results = this.Invoke("GetDocumentHeadersXML", new object[] {
                        userid,
                        customerid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDocumentHeadersXML(string userid, string customerid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDocumentHeadersXML", new object[] {
                        userid,
                        customerid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetDocumentHeadersXML(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetDocumentHeadersXMLWithFilters", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDocumentHeadersXMLWithFilters(string userid, string customerid, long fromTicks, long toTicks, string docStatusID, string docTypeID, string hasBeenChecked, string hasBeenExecuted) {
            object[] results = this.Invoke("GetDocumentHeadersXMLWithFilters", new object[] {
                        userid,
                        customerid,
                        fromTicks,
                        toTicks,
                        docStatusID,
                        docTypeID,
                        hasBeenChecked,
                        hasBeenExecuted});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDocumentHeadersXMLWithFilters(string userid, string customerid, long fromTicks, long toTicks, string docStatusID, string docTypeID, string hasBeenChecked, string hasBeenExecuted, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDocumentHeadersXMLWithFilters", new object[] {
                        userid,
                        customerid,
                        fromTicks,
                        toTicks,
                        docStatusID,
                        docTypeID,
                        hasBeenChecked,
                        hasBeenExecuted}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetDocumentHeadersXMLWithFilters(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/CreateCustomer", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreateCustomer(string taxCode, string customer_code, string userid, string store, string priceCatalog) {
            object[] results = this.Invoke("CreateCustomer", new object[] {
                        taxCode,
                        customer_code,
                        userid,
                        store,
                        priceCatalog});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateCustomer(string taxCode, string customer_code, string userid, string store, string priceCatalog, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateCustomer", new object[] {
                        taxCode,
                        customer_code,
                        userid,
                        store,
                        priceCatalog}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndCreateCustomer(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetImagesLink", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetImagesLink(string userID, string[] imageGuids) {
            object[] results = this.Invoke("GetImagesLink", new object[] {
                        userID,
                        imageGuids});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetImagesLink(string userID, string[] imageGuids, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetImagesLink", new object[] {
                        userID,
                        imageGuids}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetImagesLink(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/DoesExistsAndIsActive", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] DoesExistsAndIsActive(string[] objectIds, string objectType, string userid) {
            object[] results = this.Invoke("DoesExistsAndIsActive", new object[] {
                        objectIds,
                        objectType,
                        userid});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDoesExistsAndIsActive(string[] objectIds, string objectType, string userid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DoesExistsAndIsActive", new object[] {
                        objectIds,
                        objectType,
                        userid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndDoesExistsAndIsActive(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetInactiveObjects", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetInactiveObjects(long mobileUpdatedOn, string objectType, string userid) {
            object[] results = this.Invoke("GetInactiveObjects", new object[] {
                        mobileUpdatedOn,
                        objectType,
                        userid});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInactiveObjects(long mobileUpdatedOn, string objectType, string userid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInactiveObjects", new object[] {
                        mobileUpdatedOn,
                        objectType,
                        userid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGetInactiveObjects(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetStoreControllerGuid", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Guid GetStoreControllerGuid(string storeControllerId, string username, string password) {
            object[] results = this.Invoke("GetStoreControllerGuid", new object[] {
                        storeControllerId,
                        username,
                        password});
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetStoreControllerGuid(string storeControllerId, string username, string password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetStoreControllerGuid", new object[] {
                        storeControllerId,
                        username,
                        password}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Guid EndGetStoreControllerGuid(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetOwner", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetOwner(string storeControllerID, string username, string password) {
            object[] results = this.Invoke("GetOwner", new object[] {
                        storeControllerID,
                        username,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetOwner(string storeControllerID, string username, string password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetOwner", new object[] {
                        storeControllerID,
                        username,
                        password}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetOwner(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetStoreControllerSettings", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetStoreControllerSettings(string storeControllerID, string username, string password) {
            object[] results = this.Invoke("GetStoreControllerSettings", new object[] {
                        storeControllerID,
                        username,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetStoreControllerSettings(string storeControllerID, string username, string password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetStoreControllerSettings", new object[] {
                        storeControllerID,
                        username,
                        password}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetStoreControllerSettings(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetStoreOfStoreController", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Guid GetStoreOfStoreController(string storeControllerId, string username, string password) {
            object[] results = this.Invoke("GetStoreOfStoreController", new object[] {
                        storeControllerId,
                        username,
                        password});
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetStoreOfStoreController(string storeControllerId, string username, string password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetStoreOfStoreController", new object[] {
                        storeControllerId,
                        username,
                        password}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Guid EndGetStoreOfStoreController(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetDefaultCustomerOfStoreController", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Guid GetDefaultCustomerOfStoreController(string storeControllerId, string username, string password) {
            object[] results = this.Invoke("GetDefaultCustomerOfStoreController", new object[] {
                        storeControllerId,
                        username,
                        password});
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDefaultCustomerOfStoreController(string storeControllerId, string username, string password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDefaultCustomerOfStoreController", new object[] {
                        storeControllerId,
                        username,
                        password}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Guid EndGetDefaultCustomerOfStoreController(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://weborders.masoutis.gr/GetMobileFilelist", RequestNamespace="https://weborders.masoutis.gr/", ResponseNamespace="https://weborders.masoutis.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetMobileFilelist() {
            object[] results = this.Invoke("GetMobileFilelist", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetMobileFilelist(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetMobileFilelist", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[][] EndGetMobileFilelist(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[][])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://weborders.masoutis.gr/")]
    public partial class TDocumentStatus {
        
        private System.Guid oidField;
        
        private string descriptionField;
        
        private bool isDefaultField;
        
        /// <remarks/>
        public System.Guid Oid {
            get {
                return this.oidField;
            }
            set {
                this.oidField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDefault {
            get {
                return this.isDefaultField;
            }
            set {
                this.isDefaultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://weborders.masoutis.gr/")]
    public partial class TDocumentHeader {
        
        private long finalizedDateTimeField;
        
        private double netTotalField;
        
        private double discountField;
        
        private double finalField;
        
        /// <remarks/>
        public long finalizedDateTime {
            get {
                return this.finalizedDateTimeField;
            }
            set {
                this.finalizedDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public double netTotal {
            get {
                return this.netTotalField;
            }
            set {
                this.netTotalField = value;
            }
        }
        
        /// <remarks/>
        public double discount {
            get {
                return this.discountField;
            }
            set {
                this.discountField = value;
            }
        }
        
        /// <remarks/>
        public double final {
            get {
                return this.finalField;
            }
            set {
                this.finalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://weborders.masoutis.gr/")]
    public partial class TAppSettings {
        
        private bool barcodePadField;
        
        private bool codePadField;
        
        private bool discountPermitedField;
        
        private string barcodePadCharField;
        
        private string codePadCharField;
        
        private int barcodePadLengthField;
        
        private int codePadLengthField;
        
        private int computeDigitsField;
        
        private int computeValueDigitsField;
        
        private int displayDigitsField;
        
        private int displayValueDigitsField;
        
        /// <remarks/>
        public bool BarcodePad {
            get {
                return this.barcodePadField;
            }
            set {
                this.barcodePadField = value;
            }
        }
        
        /// <remarks/>
        public bool CodePad {
            get {
                return this.codePadField;
            }
            set {
                this.codePadField = value;
            }
        }
        
        /// <remarks/>
        public bool DiscountPermited {
            get {
                return this.discountPermitedField;
            }
            set {
                this.discountPermitedField = value;
            }
        }
        
        /// <remarks/>
        public string BarcodePadChar {
            get {
                return this.barcodePadCharField;
            }
            set {
                this.barcodePadCharField = value;
            }
        }
        
        /// <remarks/>
        public string CodePadChar {
            get {
                return this.codePadCharField;
            }
            set {
                this.codePadCharField = value;
            }
        }
        
        /// <remarks/>
        public int BarcodePadLength {
            get {
                return this.barcodePadLengthField;
            }
            set {
                this.barcodePadLengthField = value;
            }
        }
        
        /// <remarks/>
        public int CodePadLength {
            get {
                return this.codePadLengthField;
            }
            set {
                this.codePadLengthField = value;
            }
        }
        
        /// <remarks/>
        public int ComputeDigits {
            get {
                return this.computeDigitsField;
            }
            set {
                this.computeDigitsField = value;
            }
        }
        
        /// <remarks/>
        public int ComputeValueDigits {
            get {
                return this.computeValueDigitsField;
            }
            set {
                this.computeValueDigitsField = value;
            }
        }
        
        /// <remarks/>
        public int DisplayDigits {
            get {
                return this.displayDigitsField;
            }
            set {
                this.displayDigitsField = value;
            }
        }
        
        /// <remarks/>
        public int DisplayValueDigits {
            get {
                return this.displayValueDigitsField;
            }
            set {
                this.displayValueDigitsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://weborders.masoutis.gr/")]
    public partial class TStore {
        
        private System.Guid oidField;
        
        private string codeField;
        
        private string nameField;
        
        private bool isCentralStoreField;
        
        private long updatedOnField;
        
        /// <remarks/>
        public System.Guid Oid {
            get {
                return this.oidField;
            }
            set {
                this.oidField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCentralStore {
            get {
                return this.isCentralStoreField;
            }
            set {
                this.isCentralStoreField = value;
            }
        }
        
        /// <remarks/>
        public long UpdatedOn {
            get {
                return this.updatedOnField;
            }
            set {
                this.updatedOnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://weborders.masoutis.gr/")]
    public partial class TUserStoreAccess {
        
        private System.Guid userIDField;
        
        private System.Guid storeIDField;
        
        private long updatedOnField;
        
        /// <remarks/>
        public System.Guid UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid StoreID {
            get {
                return this.storeIDField;
            }
            set {
                this.storeIDField = value;
            }
        }
        
        /// <remarks/>
        public long UpdatedOn {
            get {
                return this.updatedOnField;
            }
            set {
                this.updatedOnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://weborders.masoutis.gr/")]
    public partial class TCustomer {
        
        private string codeField;
        
        private string companyNameField;
        
        private string taxCodeField;
        
        private System.Guid oidField;
        
        private System.Guid priceListOidField;
        
        private System.Guid vatLevelField;
        
        private System.Guid storeOidField;
        
        private string defaultAddressField;
        
        private string defaultPhoneField;
        
        private long updateOnField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string TaxCode {
            get {
                return this.taxCodeField;
            }
            set {
                this.taxCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid Oid {
            get {
                return this.oidField;
            }
            set {
                this.oidField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid PriceListOid {
            get {
                return this.priceListOidField;
            }
            set {
                this.priceListOidField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid VatLevel {
            get {
                return this.vatLevelField;
            }
            set {
                this.vatLevelField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid StoreOid {
            get {
                return this.storeOidField;
            }
            set {
                this.storeOidField = value;
            }
        }
        
        /// <remarks/>
        public string DefaultAddress {
            get {
                return this.defaultAddressField;
            }
            set {
                this.defaultAddressField = value;
            }
        }
        
        /// <remarks/>
        public string DefaultPhone {
            get {
                return this.defaultPhoneField;
            }
            set {
                this.defaultPhoneField = value;
            }
        }
        
        /// <remarks/>
        public long UpdateOn {
            get {
                return this.updateOnField;
            }
            set {
                this.updateOnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://weborders.masoutis.gr/")]
    public partial class TInvalidItem {
        
        private System.Guid itemOidField;
        
        private InactiveItemReason reasonField;
        
        /// <remarks/>
        public System.Guid ItemOid {
            get {
                return this.itemOidField;
            }
            set {
                this.itemOidField = value;
            }
        }
        
        /// <remarks/>
        public InactiveItemReason Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://weborders.masoutis.gr/")]
    public enum InactiveItemReason {
        
        /// <remarks/>
        INACTIVE,
        
        /// <remarks/>
        NOPRICE,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://weborders.masoutis.gr/")]
    public partial class TransferedDocumentDetail {
        
        private string barcodeField;
        
        private string itemCodeField;
        
        private string itemNameField;
        
        private double finalUnitPriceField;
        
        private double firstDiscountField;
        
        private double grossTotalField;
        
        private double unitPriceField;
        
        private double qtyField;
        
        private double netTotalField;
        
        private double netTotalAfterDiscountField;
        
        private double secondDiscountField;
        
        private double totalDiscountField;
        
        private double totalVatAmountField;
        
        private double unitPriceAfterDiscountField;
        
        private double vatAmountField;
        
        private double vatFactorField;
        
        private System.Guid itemOidField;
        
        /// <remarks/>
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        public string ItemCode {
            get {
                return this.itemCodeField;
            }
            set {
                this.itemCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        public double FinalUnitPrice {
            get {
                return this.finalUnitPriceField;
            }
            set {
                this.finalUnitPriceField = value;
            }
        }
        
        /// <remarks/>
        public double FirstDiscount {
            get {
                return this.firstDiscountField;
            }
            set {
                this.firstDiscountField = value;
            }
        }
        
        /// <remarks/>
        public double GrossTotal {
            get {
                return this.grossTotalField;
            }
            set {
                this.grossTotalField = value;
            }
        }
        
        /// <remarks/>
        public double UnitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
            }
        }
        
        /// <remarks/>
        public double Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        public double NetTotal {
            get {
                return this.netTotalField;
            }
            set {
                this.netTotalField = value;
            }
        }
        
        /// <remarks/>
        public double NetTotalAfterDiscount {
            get {
                return this.netTotalAfterDiscountField;
            }
            set {
                this.netTotalAfterDiscountField = value;
            }
        }
        
        /// <remarks/>
        public double SecondDiscount {
            get {
                return this.secondDiscountField;
            }
            set {
                this.secondDiscountField = value;
            }
        }
        
        /// <remarks/>
        public double TotalDiscount {
            get {
                return this.totalDiscountField;
            }
            set {
                this.totalDiscountField = value;
            }
        }
        
        /// <remarks/>
        public double TotalVatAmount {
            get {
                return this.totalVatAmountField;
            }
            set {
                this.totalVatAmountField = value;
            }
        }
        
        /// <remarks/>
        public double UnitPriceAfterDiscount {
            get {
                return this.unitPriceAfterDiscountField;
            }
            set {
                this.unitPriceAfterDiscountField = value;
            }
        }
        
        /// <remarks/>
        public double VatAmount {
            get {
                return this.vatAmountField;
            }
            set {
                this.vatAmountField = value;
            }
        }
        
        /// <remarks/>
        public double VatFactor {
            get {
                return this.vatFactorField;
            }
            set {
                this.vatFactorField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid ItemOid {
            get {
                return this.itemOidField;
            }
            set {
                this.itemOidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://weborders.masoutis.gr/")]
    public enum UserType {
        
        /// <remarks/>
        SUPPLIER,
        
        /// <remarks/>
        CUSTOMER,
        
        /// <remarks/>
        BOTH,
        
        /// <remarks/>
        ADMIN,
        
        /// <remarks/>
        NONE,
    }
}
