//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5485.
// 
#pragma warning disable 1591

namespace ITS.MobileAtStore.Common.WRMService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MobileAtStoreServiceSoap", Namespace="http://www.its.net.gr/")]
    public partial class MobileAtStoreService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidateOrderItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostDocumentOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MobileAtStoreService() {
            this.Url = global::ITS.MobileAtStore.Common.Properties.Settings.Default.ITS_Mobile_Store_Common_WRMService_MobileAtStoreService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidateOrderItemsCompletedEventHandler ValidateOrderItemsCompleted;
        
        /// <remarks/>
        public event PostDocumentCompletedEventHandler PostDocumentCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.its.net.gr/ValidateOrderItems", RequestNamespace="http://www.its.net.gr/", ResponseNamespace="http://www.its.net.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public InvalidItem[] ValidateOrderItems(string xmlString) {
            object[] results = this.Invoke("ValidateOrderItems", new object[] {
                        xmlString});
            return ((InvalidItem[])(results[0]));
        }
        
        /// <remarks/>
        public void ValidateOrderItemsAsync(string xmlString) {
            this.ValidateOrderItemsAsync(xmlString, null);
        }
        
        /// <remarks/>
        public void ValidateOrderItemsAsync(string xmlString, object userState) {
            if ((this.ValidateOrderItemsOperationCompleted == null)) {
                this.ValidateOrderItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateOrderItemsOperationCompleted);
            }
            this.InvokeAsync("ValidateOrderItems", new object[] {
                        xmlString}, this.ValidateOrderItemsOperationCompleted, userState);
        }
        
        private void OnValidateOrderItemsOperationCompleted(object arg) {
            if ((this.ValidateOrderItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateOrderItemsCompleted(this, new ValidateOrderItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.its.net.gr/PostDocument", RequestNamespace="http://www.its.net.gr/", ResponseNamespace="http://www.its.net.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PostDocument(string data) {
            object[] results = this.Invoke("PostDocument", new object[] {
                        data});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PostDocumentAsync(string data) {
            this.PostDocumentAsync(data, null);
        }
        
        /// <remarks/>
        public void PostDocumentAsync(string data, object userState) {
            if ((this.PostDocumentOperationCompleted == null)) {
                this.PostDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostDocumentOperationCompleted);
            }
            this.InvokeAsync("PostDocument", new object[] {
                        data}, this.PostDocumentOperationCompleted, userState);
        }
        
        private void OnPostDocumentOperationCompleted(object arg) {
            if ((this.PostDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostDocumentCompleted(this, new PostDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.its.net.gr/")]
    public partial class InvalidItem {
        
        private System.Guid itemOidField;
        
        private string itemCodeField;
        
        private string barcodeField;
        
        private InactiveItemReason reasonField;
        
        /// <remarks/>
        public System.Guid ItemOid {
            get {
                return this.itemOidField;
            }
            set {
                this.itemOidField = value;
            }
        }
        
        /// <remarks/>
        public string ItemCode {
            get {
                return this.itemCodeField;
            }
            set {
                this.itemCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        public InactiveItemReason Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.its.net.gr/")]
    public enum InactiveItemReason {
        
        /// <remarks/>
        INACTIVE,
        
        /// <remarks/>
        NOPRICE,
        
        /// <remarks/>
        NOT_FOUND,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void ValidateOrderItemsCompletedEventHandler(object sender, ValidateOrderItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateOrderItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateOrderItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InvalidItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InvalidItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void PostDocumentCompletedEventHandler(object sender, PostDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591